# Generated by Django 5.1.3 on 2024-11-27 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='delivery_option',
            field=models.CharField(choices=[('retiro', 'Retiro en Tienda'), ('despacho', 'Despacho a Domicilio')], max_length=50),
        ),
        migrations.AlterField(
            model_name='sale',
            name='payment_method',
            field=models.CharField(choices=[('tarjeta', 'Tarjeta de Débito'), ('efectivo', 'Pago en Efectivo')], max_length=50),
        ),
    ]
